grails:
  gorm:
    multiTenancy:
      mode: DATABASE # <1>
      tenantResolverClass: com.hmtmcse.saas.TenantIdResolver # <2>
    reactor:
      events: false


hibernate:
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
dataSource:
  pooled: true
  jmxExport: true
  driverClassName: com.mysql.cj.jdbc.Driver
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  username: root # <1>
  password: "" # <1>
  dbCreate: update
  url: "jdbc:mysql://localhost/multi_tenant?useUnicode=yes&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
